### ISSUE TITLE
050-install-cinnamon-core-v1.sh failed : dmd-display-manager does not exist

### ISSUE THREAD

**Issue by kxli-Ai** [erikdubois/ArchCinnamon#3]
Hi , erik
【vbox 5.0】
【arch linux  2017.10.1.iso】

020-040 is ok
050-install-cinnamon-core-v1.sh failed : dmd-display-manager does not exist
sudo reboot failed desktop

**Comment by erikdubois** [comment]
Looks like a typo to me 
mdm-display-manager - does that exist ?
i am on archmerged now

**Comment by keepkay** [comment]
050-install-cinnamon-core-v1.sh

> sudo pacman -S mdm-display-manager
error: target not found: mdm-display-manage

**Comment by TheNicholasNick** [comment]
FYI - I already raised this....
#1 

Edit: The script fails because a dependency for mdm is not met.

**Comment by kxli-Ai** [comment]
@SoreGums Thanks


but I'll try it your way
Vbox has not been compiled and installed for more than 5 hours
Disk = 40 g
Swap = 2 g
/tmp = 2 g

Final use：
pacman -Sy lightdm lightdm-kde-greeter
systemctl enable lightdm

**Comment by erikdubois** [comment]
i am using also lightdm with my archmerge installations
gdm gives me also issues now...
mdm can give also issues.
